const mockResponse = {
  data: {
    contacts: [
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "1",
        messagesReceived: 0,
        messagesSent: 0,
        name: "David",
        phoneNumber: "7758869952",
        platformNames: [],
        tags: [],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "2",
        messagesReceived: 0,
        messagesSent: 0,
        name: "test12",
        phoneNumber: "111111",
        platformNames: [],
        tags: [],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "3",
        messagesReceived: 0,
        messagesSent: 0,
        name: "Demo12",
        phoneNumber: "1234567800",
        platformNames: [],
        tags: [],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "4",
        messagesReceived: 0,
        messagesSent: 0,
        name: "janeDoe1",
        phoneNumber: "12341101",
        platformNames: [],
        tags: [],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "5",
        messagesReceived: 0,
        messagesSent: 0,
        name: "janeDoe1",
        phoneNumber: "123410",
        platformNames: [],
        tags: [],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "6",
        messagesReceived: 0,
        messagesSent: 0,
        name: "test1",
        phoneNumber: "1234512345",
        platformNames: [],
        tags: [],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "7",
        messagesReceived: 0,
        messagesSent: 0,
        name: "Demo4657656566775675465562",
        phoneNumber: "3774",
        platformNames: [],
        tags: [],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "8",
        messagesReceived: 0,
        messagesSent: 0,
        name: "janeDoe",
        phoneNumber: "12340",
        platformNames: [],
        tags: [],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "9",
        messagesReceived: 0,
        messagesSent: 0,
        name: "string",
        phoneNumber: "1234567800",
        platformNames: [],
        tags: [{ name: "string", value: "string" }],
        type: "individual",
      },
      {
        accountId: "acc_a001994b-918b-4939-85_1a37",
        createdAt: "",
        id: "10",
        messagesReceived: 0,
        messagesSent: 0,
        name: "Mamie Lawrence",
        phoneNumber: "19594982324",
        platformNames: [],
        tags: [{ name: "duis" }, { name: "eu" }, { name: "magna" }],
        type: "individual",
      },
    ],
  },
};

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  get: jest.fn().mockResolvedValue(mockResponse),
  request: jest.fn().mockResolvedValue({ data: { access_token: "token" } }),
};

