name: Deployment excercise 2
on: 
  push:
    branches:
      - "main"
      - "test/**"
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:fix
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Publish JS Filename
        id: publish
        run: find build/static/js/main*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-Files
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacte
        uses: actions/download-artifact@v3
        with:
          name: Build-Files
          path: build
      - name: List Build Files
        run: ls -Ral build/
      - name: Output files
        run: echo ${{ needs.build.outputs.script-file }}
      - name: Deploy Code
        run: echo "Deploying..."
