name: Deployment excercise 1
on:
  pull_request:
    types:
      - opened
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint:fix
      - name: Test
        run: yarn test
      - name: Build Code
        run: yarn run build
      - name: Deploy Code
        run: echo "Deploying..."