name: Handle Issues
on:
  issues:
    branches:
      - "main"
      - "test/**"
    paths-ignore:
        - ".github/workflows/*"
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"